baseurl = "https://tgzl.github.io/"
title = "ç³–æœğŸ¬çš„å°å±‹"
enableRobotsTXT = true
enableEmoji = true
theme = "jane"

hasCJKLanguage = true     # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡\æ—¥æ–‡\éŸ©æ–‡
paginate = 10             # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
rssLimit = 20             # é™åˆ¶ Rss æ–‡ç« è¾“å‡ºæ•°é‡
disqusShortname = "https-tgzl.github-io/"      # disqus_shortname
#googleAnalytics = "UA-42862533-1"      # UA-XXXXXXXX-X
copyright = "ç³–æœkoco"            # é»˜è®¤ä¸ºä¸‹é¢é…ç½®çš„author.name â†“
# uglyURLs = true         # more info: https://gohugo.io/content-management/urls/#ugly-urls

# çªå‡ºæ˜¾ç¤ºé€‰é¡¹. See https://gohugo.io/content-management/syntax-highlighting/
PygmentsCodeFences = true # ä½¿ç”¨githubé£æ ¼çš„ä»£ç å›´æ å¯ç”¨è¯­æ³•çªå‡ºæ˜¾ç¤º
PygmentsUseClasses = true # ä½¿ç”¨cssç±»æ ¼å¼åŒ–çªå‡ºæ˜¾ç¤ºçš„ä»£ç 
PygmentsCodefencesGuessSyntax = true #Pygmentsä»£ç å›´æ çŒœæµ‹è¯­æ³•
PygmentsOptions = "linenos=table" #pygmentsé€‰é¡¹

# è¯­è¨€æ”¯æŒ # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # è¦ä½¿ç”¨çš„é»˜è®¤è¯­è¨€
[languages.zh-cn]
  languageCode = "zh-cn"

[author]                                   # å¿…éœ€
  name = "ç³–æœğŸ¬Koco"

[sitemap]                                  # å¿…éœ€
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]                    # é…ç½®ç›®å½•
  name = "é¦–é¡µ"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "å½’æ¡£"
  weight = 20
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "æ ‡ç­¾"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "åˆ†ç±»"
  weight = 40
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "å…³äº"
  weight = 50
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "GitHub"
  weight = 60
  url = "https://github.com/tgzl"

[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  # uglyURLs = true          # åœ¨ç½‘ç«™ä¸­ä½¿ç”¨uglyurlåå¿…é¡»è®¾ç½®ä¸ºtrueï¼ˆè§ä¸Šæ–‡ï¼‰ã€‚å› ä¸º$.site.uglyurlæ— æ³•å¯¼å…¥ã€‚
  since = "2019"            # Site creation time          # ç«™ç‚¹å»ºç«‹æ—¶é—´
  homeFullContent = false   # å¦‚æœé”™è¯¯ï¼Œè¯·åœ¨ä¸»é¡µä¸Šæ˜¾ç¤ºæ–‡ç« æ‘˜è¦ã€‚å…¶ä»–çš„éƒ½æ˜¾ç¤ºäº†å…¨éƒ¨çš„å†…å®¹ã€‚
  rssFullContent = true     # å¦‚æœä¸ºfalseï¼Œåˆ™ä½¿ç”¨rssæè¦è€Œä¸æ˜¯æ‘˜è¦

  # site info (optional)         # ç«™ç‚¹ä¿¡æ¯ï¼ˆå¯é€‰ï¼Œä¸éœ€è¦çš„å¯ä»¥ç›´æ¥æ³¨é‡Šæ‰ï¼‰
  logoTitle = "ç³–æœğŸ¬çš„å°å±‹"         # é»˜è®¤å€¼: ä¸Šé¢è®¾ç½®çš„titleå€¼
  keywords = ["Koco", "go", "golang","åšå®¢","blog"] #å…³é”®è¯
  description = "ç³–æœKocoçš„ç”Ÿæ´»åˆ†äº«ğŸ”§ç»ƒä¹ âœï¸åˆ·é¢˜ğŸ“ç¬”è®°ğŸ“šå­¦ä¹ ğŸ’¬äº¤æµ~" #æè¿°

  # å½’æ¡£ã€æ ‡ç­¾ã€åˆ†ç±»æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°ç›®ï¼Œå»ºè®®ä¿®æ”¹ä¸ºä¸€ä¸ªè¾ƒå¤§çš„å€¼
  archive-paginate = 50

  # åˆ†é¡µæ ·å¼ï¼Œé»˜è®¤ä½¿ç”¨å¸¦ç¼–å·çš„åˆ†é¡µé“¾æ¥
  # å¦‚æœä¸ºçœŸï¼Œè¯·ä½¿ç”¨åŸå§‹çš„â€œä¸Šä¸€ä¸ªâ€å’Œâ€œä¸‹ä¸€ä¸ªâ€é“¾æ¥ã€‚
  # paginateOriginalStyle = true

  # è¦ä½¿ç”¨çš„æ—¥æœŸæ ¼å¼ï¼›ç”¨äºæœ‰æ•ˆæ ¼å¼çš„åˆ—è¡¨, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # æ˜¯å¦æ˜¾ç¤ºå­—æ•°ç»Ÿè®¡ä¸é˜…è¯»æ—¶é—´
  moreMeta = true

# åœ¨èœå•ä¸­æ˜¾ç¤ºè¯­è¨€é€‰æ‹©å™¨
  showMenuLanguageChooser = false

# åœ¨æ–‡ç« ä¸‹é¢æ˜¾ç¤ºä½œè€…ä¿¡æ¯
  showAuthorInfo = true 

  # ä¸€äº›å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½ï¼Œåœ¨ archetypes/default.md æŸ¥çœ‹æ›´å¤šä¿¡æ¯ã€‚
  toc = true                # æ˜¯å¦å¼€å¯ç›®å½•
  photoswipe = true         # æ˜¯å¦å¯ç”¨PhotoSwipeï¼ˆå›¾ç‰‡å¯ç‚¹å‡»ï¼‰
  bootcdn = false           # æ˜¯å¦ä½¿ç”¨bootcdn(@Deprecated: è¯·ä½¿ç”¨[params.publicCDN])
  mathjax = true           # æ˜¯å¦ä½¿ç”¨mathjaxï¼ˆæ•°å­¦å…¬å¼ï¼‰
  katex = false             # æ˜¯å¦ä½¿ç”¨katexï¼ˆjavascriptåº“ï¼‰see https://github.com/KaTeX/KaTeX
  #å†…å®¹ç‰ˆæƒ
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  changyanAppid = ""        # ç•…è¨€ app id            
  changyanAppkey = ""       # ç•…è¨€ app key
  tencent_analytics = ""    # è…¾è®¯åˆ†æ
  baidu_push = false        # ç™¾åº¦æ¨
  baidu_analytics = ""      # ç™¾åº¦åˆ†æ
  baidu_verification = ""   # ç™¾åº¦éªŒè¯
  google_verification = ""  # è°·æ­ŒéªŒè¯

  # é“¾æ¥è‡ªå®šä¹‰csså’Œjs
  #  (relative to /static/css and /static/js respectively)
  customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

  # å¯ç”¨'fork me on github', see https://blog.github.com/2008-12-19-github-ribbons/
  # forkMeOnGithub = "https://github.com/tgzl/tgzl.github.io"

  # æ·»åŠ å¤‡æ¡ˆä¿¡æ¯
  # customFooter = "äº¬ICPå¤‡10000000å·-1"

  [params.publicCDN]        #å¯ç”¨å…¬å…±CDNï¼Œéœ€è‡ªè¡Œå®šä¹‰
    enable = false
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    gitmentJS = '<script src="https://cdn.jsdelivr.net/npm/gitment@0.0.3/dist/gitment.browser.min.js" crossorigin="anonymous"></script>'
    gitmentCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css" crossorigin="anonymous">'

  [params.utteranc]         # Utterancæ˜¯ä¸€ä¸ªåŸºäºGitHubé—®é¢˜çš„è¯„è®ºç³»ç»Ÿ. see https://utteranc.es
    enable = false
    repo = "xianmin/comments-for-hugo-theme-jane"    # å­˜å‚¨è¯„è®ºçš„å›è´­åè®®
    issueTerm = "pathname"

  [params.gitment]          # gitmentæ˜¯ä¸€ä¸ªåŸºäºgithubé—®é¢˜çš„è¯„è®ºç³»ç»Ÿ. see https://github.com/imsun/gitment
    owner = ""              # Your GitHub ID
    repo = ""               # å­˜å‚¨è¯„è®ºçš„å›è´­åè®®
    clientId = ""           # Your client ID
    clientSecret = ""       # Your client secret


  #[params.reward]                                         # æ–‡ç« æ‰“èµ
   # enable = false
    #wechat = "/path/to/your/wechat-qr-code.png"           # å¾®ä¿¡äºŒç»´ç 
    #alipay = "/path/to/your/alipay-qr-code.png"           # æ”¯ä»˜å®äºŒç»´ç 


 [params.social]                                         # ç¤¾äº¤é“¾æ¥
    a-email = "mailto:jbyl1205@163.com"
    g-github = "https://github.com/tgzl"
    q-bilibili = "https://space.bilibili.com/278413353"
    #p-coding = "https://github.com/tgzl/tgzl.github.io"
    #b-stack-overflow = "http://localhost:1313"
    #c-twitter = "http://localhost:1313"
    #d-facebook = "http://localhost:1313"
    #e-linkedin = "http://localhost:1313"
    #f-google = "http://localhost:1313"
    #h-weibo = "http://localhost:1313"
    #i-zhihu = "http://localhost:1313"
    #j-douban = "http://localhost:1313"
    #k-pocket = "http://localhost:1313"
    #l-tumblr = "http://localhost:1313"
    #m-instagram = "http://localhost:1313"
    #n-gitlab = "http://localhost:1313"
    #o-goodreads = "http://localhost:1313"
    #r-codeforces = "http://localhost:1313"

  [params.counter.busuanzi] # ä¸è’œå­è®¡æ•°å™¨
    enable = true

  [params.counter.leancloud]  # leancloud è®¡æ•°å™¨
    enable = false
    appId = ""
    appKey = ""

  [params.commentCount.disqus] # æ˜¾ç¤ºå–æ¶ˆè¯„è¯­çš„è®¡æ•°
    enable = false
  
  # æŒ‡å®š git ä»“åº“åœ°å€ï¼Œå¯ä»¥ç”ŸæˆæŒ‡å‘æœ€è¿‘æ›´æ–°çš„ git commit çš„é“¾æ¥ï¼Œéœ€è¦å°† enableGitInfo è®¾ç½®æˆ true.
  [params.gitInfo]
    gitRepo = "https://github.com/tgzl/tgzl.github.io"
    showCommitMessage = false

    
# jsonfeedæ”¯æŒ
# more information: https://github.com/xianmin/hugo-theme-jane/issues/23
# è¦è¾“å‡ºjsonï¼Œæœ‰å¿…è¦å–æ¶ˆæ³¨é‡Šè¿™æ®µä»£ç ï¼Œå¹¶ä½¿ç”¨hugoæ¨¡æ¿è§„èŒƒåˆ›å»ºindex.jsonfeed.jsonæ¨¡æ¿ã€‚
[outputs]
  home = ["html", "jsonfeed","rss"]
   page = ["html"]

 [outputFormats]
 [outputFormats.jsonfeed]
   mediaType = "application/json"
   baseName = "feed"
   isPlainText = true


#å¤šè¯­è¨€æ”¯æŒç¤ºä¾‹
# [langusges]
# [languages.en]
#   title = "ç³–æœğŸ¬"
#   weight = 1
# [languages.zh-cn]
#   title = "ç³–æœğŸ¬"
#   weight = 2
