baseURL = "http://localhost:1313"
languageCode = "en"
defaultContentLanguage = "en"
title = "TG zl"
theme = "KeepIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = "tgzl"
publishDir = "docs"
canonifyURLs = true

#pymentsUseClassic = false
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "tags"
    url = "/tags/"
    weight = 3

[params]
    since = 2019
    author = "TGğŸ¬ZL"               # Author's name
    subtitle = "ğŸ”¥Chang gong as surname Take Le as NameğŸ­"      # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""
    
    avatar = "images/me/avatar.png" #comment it to use gravatar
    socialShare = true
    
    description = "ç³–æœğŸ¬ZLçš„ç”Ÿæ´»åˆ†äº«ğŸ”§ç»ƒä¹ âœï¸åˆ·é¢˜ğŸ“ç¬”è®°ğŸ“šå­¦ä¹ ğŸ’¬äº¤æµ~" # site description
    keywords = "Koco go golang åšå®¢ blog" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    #email = "example@gmail.com"   #uncomment and insert your email address to use gravatar


[params.social]
    GitHub = "tgzl"
    #Linkedin = "xxxx"
    #Twitter = "xxxx"
    #Instagram = "xxxx"
    Email   = "jbyl1205@163.com"
    Telegram = "space.bilibili.com/278413353"
    #Facebook = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    Youtubelegacy = "space.bilibili.com/278413353"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "space.bilibili.com/278413353"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"
    

[params.share]
#Twitter = true
Facebook = true
#Reddit = true
Linkedin = true
#Pinterest = true
#HackerNews = true
#Mix = true
#Tumblr = true
#VKontakte = true
#Douban = true
Weibo = true

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "ç³–æœğŸ¬"

  [params.publisher]
    name = "ç³–æœğŸ¬"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

[params.gitalk]           
  owner = ""              
  repo = ""               
  clientId = ""           
  clientSecret = ""   

[params.valine]
  enable = false
  appId = 'your appId'
  appKey = 'your appKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm'
  placeholder = 'your comments ...'
  visitor = true
