# Site settings
baseurl = "https://tgzl.github.io/"
languageCode = "zh"
title = "ç³–æœğŸ¬"
theme = "plus"

# å¦‚æœç«™ç‚¹åŒ…å«cjkï¼ˆä¸­æ–‡ã€æ—¥æ–‡å’ŒéŸ©æ–‡ï¼‰å­—ç¬¦ï¼Œè¯·å°†è¯¥å€¼è®¾ç½®ä¸ºtrue
hasCJKLanguage = true

[params]
	author = "ç³–æœKoco"
	description = "ç³–æœçš„ç”Ÿæ´»åˆ†äº«ğŸ”§ç»ƒä¹ âœï¸åˆ·é¢˜ğŸ“ç¬”è®°ğŸ“šå­¦ä¹ ğŸ’¬äº¤æµ~"
	bio = "ğŸ¡éš”å£ç³–æœğŸ­å‘³ç”œè¯ä¸å¤š é•¿å¼“ä¸ºå§“ ä»¥ä¹ä¸ºåğŸ"

	# twitter = "your_twitter_id"
	# facebook = "your_facebook_id"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "koco"

	# å¯ç”¨æ‘˜è¦
	enableSummary = true
	# ä½¿ç”¨Descriptionæ›¿æ¢æ‘˜è¦ä¿¡æ¯
	useDescriptionReplaceSummary = false

	# å¦‚æœè¦ä½¿ç”¨ç™¾åº¦åˆ†æï¼Œè¯·å°†å€¼è®¾ç½®ä¸ºç™¾åº¦åˆ†æä»£ç 
	enableGoogleAnalytics = false
	# googleAnalytics = "your_google_analytics_id"
	enableBaiduAnalytics = false
	# baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = false
	# twitterå¡ç‰‡å›¾ç‰‡çš„urlï¼Œé»˜è®¤ä¸ºstatic/imagesç›®å½•ä¸‹çš„avatar.png
	# twitterCardImage = ""

	# æ·»åŠ è‡ªå®šä¹‰èµ„æºåŠå…¶ç›¸å¯¹äºé™æ€æ–‡ä»¶å¤¹çš„è·¯å¾„
	customCSS = []
	customJS  = []

	# ä¸‹é¢çš„å˜é‡ä¹Ÿæ˜¯å¯é€‰çš„ï¼Œå¯ä»¥ç”¨æ¥,ç¿»è¯‘æˆ–è‡ªå®šä¹‰ä¸»é¢˜çš„æ¯ä¸ªå­—ç¬¦ä¸²

	# å¯¼èˆªé“¾æ¥
	home = "ä¸»é¡µ"
	about = "å…³äº"
	tags = "æ ‡ç­¾"
	archive = "ç›®å½•"
	subscribe = "è®¢é˜…"

	olderPosts = "ğŸš€ä¸‹ä¸€é¡µğŸš€"
	newerPosts = "ğŸ›ä¸Šä¸€é¡µğŸ›"
	copyright = ""
	copyrighttime = "2019"

	# åœ¨å•é¡µä¸­æ˜¾ç¤ºæœ€æ–°æ–‡ç« 
	showLatestPosts = true
	readMore = "ğŸ“‘é˜…è¯»æ›´å¤š"

	# åˆ†äº«
	# enableShare = true
	# tweet = ""
	# share = ""

	# 404 é¡µé¢
	title404 = "ğŸ™ˆç½‘å€è¿·è·¯äº†^_^~"
	subtitle404 = "æˆ‘çœŸçš„è¿·è·¯äº†ğŸš‘ğŸš‘ğŸš‘ğŸš‘ğŸš‘ğŸš‘ğŸš‘ğŸš‘"

	# ä¸ºé¡µè„šä¸­çš„ç¤¾äº¤å›¾æ ‡é€‰æ‹©å­—ä½“ã€‚è¦ä¹ˆæ˜¯â€œMono Socialâ€è¦ä¹ˆæ˜¯â€œFont Awesomeâ€
	iconFont = "font-awesome"
  	# å¦‚æœä½¿ç”¨monoä½œä¸ºå­—ä½“åœ†ã€åœ†å½¢æˆ–ç©ºï¼Œåˆ™ç¤¾äº¤å›¾æ ‡çš„æ ·å¼å¯ä»¥ä¸åŒã€‚
  	socialIconStyle = ""


# åœ¨ä¸‹é¢æ·»åŠ å…¶ä»–ç¤¾äº¤é“¾æ¥æ¡ç›®
[social]
	github-square = "https://www.github.com/tgzl"
	file-code-o = "https://github.com/tgzl/tgzl.github.io"
	# qq = "/me/szm.png"
	# weixin = "/me/szm.png"
	youtube-play  = "https://space.bilibili.com/278413353"
	rss-square = "/index.xml"
	envelope-square = "mailto:jbyl1205@163.com"
	
